[env:m5stack-cardcomputer]
platform = espressif32
board = m5stack-cardcomputer
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_freq = 80Mhz

board_upload.flash_size = 4MB
board_upload.maximum_ram_size = 327680

monitor_speed = 115200
upload_speed = 460800

lib_deps =
    m5stack/M5Stack @ ^0.4.0
    links2004/WebSocketsClient @ ^2.3.5
    bblanchon/ArduinoJson @ ^6.19.4
    Bodmer/TJpg_Decoder @ ^1.0.6

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM=1
    -mfix-esp32-psram-cache-issue
    -O2
    -Wall
